name = "example"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
mist = ">= 1.2.0 and < 2.0.0"
wisp = ">= 0.15.0 and < 1.0.0"
lustre = ">= 4.3.0 and < 5.0.0"
formal = { path = ".." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
