name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.12.0-rc1"
          rebar3-version: "3"
      - run: gleam test --target erlang
      - run: gleam test --target javascript
      - run: cd examples/backend-with-wisp && gleam test
      - run: cd examples/frontend-with-lustre && gleam test

      - run: gleam format --check
      - run: cd examples/backend-with-wisp && gleam format --check
      - run: cd examples/frontend-with-lustre && gleam test
